language:
  - minimal

install:
  - docker pull jjmerelo/p5-devqagrx:latest
  - docker images

script: 
  - docker run -t  --env TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -v $TRAVIS_BUILD_DIR:/test jjmerelo/p5-devqagrx:latest
