name: "Comprueba README"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'
  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'

jobs:
  OrtografiaReadme:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: sudo apt-get update && sudo apt-get install -y libtext-hunspell-perl autopoint
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instala módulos
        run: sudo cpan Test::Text Tap::Harness
      - name: Ejecuta los tests
        run: |
          curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
          curl https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic
          echo "use Test::Text; just_check( '.','.', 'Spanish' ); " > just_check.t
          rm proyectos.md asistentes.md # No nos interesan
          cat just_check.t
          perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if $harness->runtests( "just_check.t" )->failed;'
