name: "Comprueba hitos e issues"
on:
  pull_request:
    paths:
      - 'proyectos.md'

jobs:
  obtain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio del diff
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Comprueba hitos e issues
        uses: JJ/repo-in-diff-gh-action@releases/v1
        with:
          github-token: ${{github.token}}
          minVersion: "4.0.0"
          minPRs: 1
          minMilestones: 1
      - name: Comprueba que exista el tablero
        if: env.version >= "v1"
        with:
          github-token: ${{github.token}}
        script: |
           const user = process.env.user
           const repo = process.env.repo
           const projects = github.request( 'GET /repos/{user}/{repo}/projects', {
               user: user,
               repo: repo,
           })
           console.log( projects )
           if ( projects.data.length > 0 ) {
               core.setFailed("❌ Debe haber un proyecto (para el tablero)")
           } else {
               console.log( "✅ Tenemos un proyecto para el tablero ")
           }
